app/models.py
# Contains the domain models of the application

from flask_login import UserMixin

from . import db, login_manager


class Genre(db.Model):
    __tablename__ = 'genre'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(250), unique=True)
    movies = db.relationship('Movie', back_populates='genre')

    @property
    def serialize(self):
        return {
            'id': self.id,
            'movies': [m.serialize for m in self.movies]
        }


class Movie(db.Model):
    __tablename__ = 'movie'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(250), nullable=False)
    description = db.Column(db.Text)
    image_url = db.Column(db.String(250))
    year = db.Column(db.String(4))
    genre_name = db.Column(db.String(250), db.ForeignKey('genre.name'))
    genre = db.relationship('Genre', back_populates='movies')

    @property
    def serialize(self):
        return {
            'id': self.id,
            'title': self.title,
            'description': self.description,
            'image-url': self.image_url,
            'year': self.year
        }


class User(UserMixin, db.Model):
    __tablename__ = 'user'

    id = db.Column(db.Integer, primary_key=True)
    social_id = db.Column(db.String(64), nullable=False, unique=True)


@login_manager.user_loader
def load_user(id):
    return User.query.get(int(id))

app/main/forms.py
from flask_wtf import Form
from wtforms import StringField, TextAreaField, SubmitField, IntegerField
from wtforms.fields.html5 import URLField
from wtforms.validators import DataRequired


class MovieForm(Form):
    title = StringField('title', validators=[DataRequired()])
    description = TextAreaField('description')
    year = IntegerField('year')
    image = URLField('image')
    submit = SubmitField('Submit')

app/__init__.py
# Application factory

import os

from flask import Flask
from flask_bootstrap import Bootstrap
from flask_github import GitHub
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy

bootstrap = Bootstrap()
db = SQLAlchemy()
github = GitHub()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_message = 'auth.login'


def create_app():
    """ Creates the app and initializes the components """
    app = Flask(__name__)

    app.config['SECRET_KEY'] = os.environ.get(
        'catalog_secret_key') or 'voll geheim!'

    postgresql_password = os.environ.get('catalog_postgresql_password')
    app.config[
        'SQLALCHEMY_DATABASE_URI'] = 'postgresql://catalog:' + \
                                     postgresql_password + '@localhost/catalog'

    app.config['GITHUB_CLIENT_ID'] = os.environ.get('catalog_github_client_id')
    app.config['GITHUB_CLIENT_SECRET'] = os.environ.get(
        'catalog_github_client_secret')

    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    github.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__, static_folder='static')

from . import views

app/main/views.py
# Contains the main routes

from flask import render_template, redirect, request, flash, jsonify, url_for
from flask_login import login_required

from .forms import MovieForm
from . import main
from .. import db
from ..models import Genre, Movie


@main.route('/')
@main.route('/catalog')
def index():
    genres = Genre.query.order_by('name asc').all()
    latest_movies = Movie.query.order_by('id desc').limit(10).all()
    return render_template('movies.html', genres=genres, movies=latest_movies)


@main.route('/catalog/<genre_name>/movies')
def movies(genre_name):
    genres = Genre.query.order_by('name asc').all()
    movies = Movie.query.filter_by(genre_name=genre_name).all()
    return render_template('movies.html', genre_name=genre_name, genres=genres,
                           movies=movies)


@main.route('/catalog/<genre_name>/<movie_title>')
def movie(genre_name, movie_title):
    movie = Movie.query.filter_by(title=movie_title).one()
    return render_template('movie.html', movie=movie)


@main.route('/catalog/<genre_name>/new', methods=['GET', 'POST'])
@login_required
def create_movie(genre_name):
    form = MovieForm()

    if form.validate_on_submit():
        new_movie = Movie(
            title=form.title.data,
            description=form.description.data,
            year=form.year.data,
            image_url=form.image.data,
            genre_name=genre_name
        )

        db.session.add(new_movie)
        db.session.commit()

        flash("New Movie added!")

        return redirect(url_for('main.movies', genre_name=genre_name))

    return render_template('create_movie.html', genre_name=genre_name,
                           form=form)


@main.route('/catalog/<movie_title>/edit', methods=['GET', 'POST'])
@login_required
def edit_movie(movie_title):
    movie = Movie.query.filter_by(title=movie_title).one()

    form = MovieForm()

    if form.validate_on_submit():
        movie.title = form.title.data
        movie.description = form.description.data
        movie.year = form.year.data
        movie.image_url = form.image.data

        db.session.add(movie)
        db.session.commit()

        flash('Movie edited!')

        return redirect(url_for('main.movies', genre_name=movie.genre_name))

    form.title.data = movie.title
    form.description.data = movie.description
    form.image.data = movie.image_url
    form.year.data = movie.year

    return render_template('edit_movie.html', movie=movie, form=form)


@main.route('/catalog/<movie_title>/delete', methods=['GET', 'POST'])
@login_required
def delete_movie(movie_title):
    movie = Movie.query.filter_by(title=movie_title).one()
    if request.method == 'POST':
        db.session.delete(movie)
        db.session.commit()

        flash('Movie deleted!')

        return redirect(url_for('main.movies', genre_name=movie.genre_name))
    else:
        return render_template('delete_movie.html', movie=movie)


@main.route('/catalog.json')
def get_json():
    """ Generates a json response of the genres and their movies """
    genres = Genre.query.all()
    return jsonify(Genres=[g.serialize for g in genres])

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Movie Catalog{% endblock %}

{% block head %}
{{ super() }}
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}">
{% endblock %}

{% block navbar %}
<div class="container-fluid">
    <nav class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed"
                        data-toggle="collapse" data-target="#navbar"
                        aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">Movie
                    Catalog</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    {% if  current_user.is_authenticated %}
                    <li><a href="{{ url_for('auth.logout') }}">Logout</a>
                    {% else %}
                    <li><a href="{{ url_for('auth.login') }}">Login</a>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</div>
{% endblock %}

{% block content %}
    <div class="container main-container">
        {% for message in get_flashed_messages() %}
            <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
            </div>
        {% endfor %}

        {% block page_content %}
        {% endblock %}
    </div>
{% endblock %}

app/templates/create_movie.html
{% extends "base.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="row">
    <div class="col-md-6">
        <h1>Add {{genre_name}} Movie</h1>
        {{ wtf.quick_form(form) }}
    </div>
</div>
{% endblock %}

app/templates/delete_movie.html
{% extends "base.html" %}
{% block page_content %}
<div class="row">
    <div class="col-md-12">
        <h1>Delete Movie</h1>
        <p>Do you really want to delete {{movie.title}}?</p>
        <form method="post" action="{{url_for('main.delete_movie', movie_title=movie.title)}}">
            <button type="submit" class="btn btn-default">Confirm</button>
            <a href="{{ url_for('main.movie', genre_name=movie.genre_name, movie_title=movie.title) }}" class="btn btn-default delete">
                        <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
                        Cancel
            </a>
        </form>
    </div>
</div>
{% endblock %}

app/templates/edit_movie.html
{% extends "base.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="row">
    <div class="col-md-6">
        <h1>Edit Movie</h1>
        {{ wtf.quick_form(form) }}
    </div>
</div>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% block page_content %}

    <div class="row">
        <div class="col-md-3">
            <div id="signInButton">
        <span class="g-signin"
            data-scope="openid email"
            data-clientid="888732429948-ldhq7qj4dvfid83j534cl3vhr7vmu2un.apps.googleusercontent.com"
            data-redirecturi="postmessage"
            data-accesstype="offline"
            data-cookiepolicy="single_host_origin"
            data-callback="signInCallback"
            data-approvalprompt="force">
        </span>
        <div id="result">

        </div>
    </div>
        </div>
    </div>
{% endblock %}

app/templates/movie.html
{% extends "base.html" %}
{% block page_content %}
<div class="row">
    <div class="col-md-11 col-md-offset-1">
        <h1>{{movie.title}} ({{movie.year}})</h1>
    </div>
</div>
<div class="row">
    <div class="col-md-2 col-md-offset-1">
        <img class="img-responsive img-rounded" src="{{movie.image_url}}">
    </div>
    <div class="col-md-6">
        <p>{{movie.description}}</p>
    </div>
</div>
{% if  current_user.is_authenticated %}
<div class="row">
    <div class="col-md-2 col-md-offset-1 margin-top">
        <a class="btn btn-default" href="{{url_for('main.edit_movie', movie_title=movie.title)}}">Edit</a>
        <a class="btn btn-danger pull-right" href="{{url_for('main.delete_movie', movie_title=movie.title)}}">Delete</a>
    </div>
</div>
{% endif %}
{% endblock %}

app/templates/movies.html
{% extends "base.html" %}
{% block page_content %}
<div class="row">
    <div class="col-md-3">
        <h1>Categories</h1>
        <div class="list-group">
            {% for genre in genres %}
            <a class="list-group-item" href="{{url_for('main.movies', genre_name=genre.name)}}">{{genre.name}}</a>
            {% endfor %}
        </div>
    </div>
    <div class="col-md-6">
        <div class="row">
            <h1>{{genre_name}} Movies ({{movies|length}} Movies)</h1>
        </div>
        <div class="row">
            {% if current_user.is_authenticated and genre_name %}
                <a class="btn btn-default margin-bottom" href="{{url_for('main.create_movie', genre_name=genre_name)}}">Add</a>
            {% endif %}
        </div>
        <div class="row">
            <div class="list-group">
                {% for movie in movies %}
                <a class="list-group-item"
                   href="{{url_for('main.movie', genre_name=movie.genre_name, movie_title=movie.title)}}">{{movie.title}}</a>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}